# Generated by Django 5.2 on 2025-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='', upload_to='menu_images/'),
            preserve_default=False,
        ),
    ]
