# Generated by Django 5.2 on 2025-04-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation_user_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], default='cash', max_length=10),
        ),
    ]
