# Generated by Django 5.2 on 2025-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_reservation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
